#!/bin/sh

# Execute as root
if [ $(id -u) -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

MYDIR=$(dirname $(readlink -f $0) )
# Read config
. $MYDIR/config

[ -n "$PIBASE" ] || exit 1

flock $CHROOT_MOUNT_LOCK $MYDIR/chroot-mount

# chroot pi fs
env LC_ALL=C debian_chroot=pi chroot $ROOTFS $@

flock $CHROOT_MOUNT_LOCK $MYDIR/chroot-umount
